name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r <(grep -oP '^[^-].*' environment.yml | grep -v '^name')
      - name: Lint
        run: |
          pip install flake8 black
          flake8 src
      - name: Tests
        run: |
          pip install pytest
          pytest -q
